# Generated by Django 3.0.4 on 2020-03-19 16:22

import core.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='user_profile_pic/default_user_thumb.jpg', upload_to=core.models.image_file_path),
        ),
    ]
