# Generated by Django 3.0.4 on 2020-03-19 17:15

import core.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200319_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='default_user_thumb.jpg', upload_to=core.models.image_file_path),
        ),
    ]
